name: documind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  doc_text_extractor: ^1.0.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.8.0
  flutter_chat_ui: ^2.9.1
  flutter_markdown: ^0.7.7+1
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^9.0.0
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  image_cropper: ^11.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.2.0
  loading_animation_widget: ^1.3.0
  ollama: ^1.0.4
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  textify: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/pakistani_boy_riding_bike.jpg